# Jekyll configs

# Site settings
baseurl: "/learn-python/"
url: "https://berufsbildung-basel.github.io"

title: Python Programming Exercices
description: >- # this means to ignore newlines until the next entry
  Website for Python Programming Exercices
show_excerpts: true
#tag_page: /tags.html
rss: "RSS"


# Build settings
markdown: kramdown
#remote_theme: just-the-docs/just-the-docs
# Using a fork until https://github.com/just-the-docs/just-the-docs/issues/729 is fixed
remote_theme: pdmosses/just-the-docs@rec-nav-2
plugins:
  - jekyll-feed
  - github-pages
  - jekyll-redirect-from

search:
  button: true

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/berufsbildung-basel/learn-python"
gh_edit_branch: "main"
gh_edit_view_mode: "tree"

footer_content: Initial 2024 version
exclude:
  - solutions
